# Generated by Django 6.0.2 on 2026-02-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], max_length=10)),
                ('property_type', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('studio', 'Studio'), ('villa', 'Villa')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('vendu', 'Vendu'), ('loué', 'Loué')], default='disponible', max_length=15)),
                ('surface', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('zip_code', models.CharField(db_index=True, max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
